version: '3.7'

# Networks
networks:
  # Internal network
  angranet:
    driver: bridge

volumes:
  authservice-mysql_data:
    driver: local

# Services
services:

  # Nginx
  angra-nginx:
    image: nginx:latest
    container_name: angra-nginx
    networks:
      angranet:
        aliases:
          - authservice.desenv
          - clientapp.desenv
    working_dir: /var/www
    volumes:
      - ./projects:/var/www
      - ./.docker/opt/docker/etc/nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
      - "443:443"
    
  angra-php81-fpm:
    build:
      context: .
      dockerfile: ./.docker/opt/docker/Dockerfile
    container_name: angra-php81-fpm
    volumes:
      - ./projects:/var/www/
    networks:
      - angranet

  angra-mysql:
    image: mysql:latest
    container_name: angra-mysql
    networks:
      - angranet
    volumes:
      - authservice-mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=auth_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=angra_user
      - MYSQL_PASSWORD=angra_password
      - MYSQL_TCP_PORT=3308
    ports:
      - "3308:3308"
